### ISSUE TITLE
Crowd nfsPermissionFixer Job runs before PVC created causing error (Run via Terraform)

### ISSUE THREAD

**Issue by smarch730** [atlassian/data-center-helm-charts#141]
I have a weird issue with the crowd chart where setting the nfsPermissionFixer value to true (thus enabling the k8s job object) errors on the helm build as the job runs before the PVC is created. This keeps the job container in a pending state. 

The event on the pending job pod is: 

> Warning  FailedScheduling  9m13s  default-scheduler  persistentvolumeclaim "crowd-shared-home" not found

According to [this](https://github.com/helm/helm/blob/main/pkg/releaseutil/kind_sorter.go#L31), the persistentVolumeClaim manifest should be applied before the job is. This doesn't seem to be the case for the crowd helm chart.. or is it just me?
This isnt an issue with other apps such as Jira... Maybe due to nfsPermissionFixer running in the statefulset init container rather than its own separate job manifest?

Running via Terraform.

**values used:**

volumes:
  localHome:
      persistentVolumeClaim:
          create: true
          storageClassName: "aws-ebs"
  sharedHome:
    persistentVolumeClaim:
        create: **true**
        storageClassName: "aws-efs"
    nfsPermissionFixer:   
        enabled: **true**

Also, storage classes already exist and are running ebs/efs volumes for Jira

**Comment by bianchi2** [comment]
@smarch730 this issue has been fixed https://github.com/atlassian-labs/data-center-helm-charts/issues/75 but Crowd Helm chart was based on the version that did not have this commit. This k8s job has been replaced with an init container in other charts.

**Comment by nghazali** [comment]
@smarch730, as we not officially support Crowd Helm chart so this issue is not prioritised at the moment. However, if you would like to add the contribution, we happily accept the PR to address this issue.

**Comment by errcode1202** [comment]
Hi  @smarch730,

We're going to close this issue. As suggested if you'd still like these changes please create a PR based on https://github.com/atlassian/data-center-helm-charts/issues/75 and we'll be happy to review.
