### ISSUE TITLE
Add schedulerName option in helm chart

### ISSUE THREAD

**Issue by bordenit** [atlassian/data-center-helm-charts#185]
When creating volumes with portworx, consider adding schedulerName in the statefulset so that users can set it to "stork".
https://docs.portworx.com/portworx-install-with-kubernetes/storage-operations/hyperconvergence/

**Comment by nanux** [comment]
Note:
We could consider adding `schedulerName:` into pod spec definition for the application statefulset. If this is undefined, we won't add it to the specification and therefore Kubernetes would pick up the default scheduler. The users would have an option to override the scheduler if they want to.

https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#scheduling

I think there is a slight risk of overcomplicating the `values.yaml` file with all potential customizations and make it confusing for administrators to configure and deploy.

@bordenit what would be the optimal solution for you?

**Comment by bordenit** [comment]
I do think it should be added to the statefulset template and have the option in values.yaml. In our environments the pods don't like to start and volume mounting fails without setting the specific schedulerName to stork.  I have a sed command currently after the helm upgrade that rewrites the schedulerName to stork which enables the pods to move more freely in the cluster.

**Comment by bordenit** [comment]
@nanux I currently add a kubectl patch just for the schedulerName. I have a collection of 3 or 4 things that I patch due to values.yaml limitations. I think this is a definite need to reduce the Atlassian ticket volume when the solution becomes fully supported.

**Comment by nanux** [comment]
@bordenit this has been merged and will be in the next release.

https://github.com/atlassian/data-center-helm-charts/pull/301
