### ISSUE TITLE
Mirror mode desired

### ISSUE THREAD

**Issue by brunzefb** [atlassian/data-center-helm-charts#187]
Hi,

I have deployed the chart, but can't figure out how to get the server in mirror mode.  Any help would be appreciated.

Best,
Friedrich

**Comment by nanux** [comment]
@brunzefb, currently it is not possible to deploy Bitbucket DC via helm chart when part of the deployment would be deployed as upstream and part as mirror(s). Is this the use case you would like to achieve or do you want to use helm charts just to deploy Bitbucket mirror?

The underlying Bitbucket image supports `APPLICATION_MODE` which can be switched to `mirror` but we haven't tested this setup with the current statefulset definition.

**Comment by nanux** [comment]
This is currently in progress https://github.com/atlassian/data-center-helm-charts/pull/265
