### ISSUE TITLE
Multiple replication not working in latest version of JIRA

### ISSUE THREAD

**Issue by abhattarai-athene** [atlassian/data-center-helm-charts#278]
The Cluster Cache Replication health check has failed in your system.

**Comment by bianchi2** [comment]
@abhattarai-athene could you please provide more info like logs, screenshots or just elaborate on what's happening when you scale Jira stateful set? Depending on what [exact error you see](https://confluence.atlassian.com/jirakb/cluster-cache-replication-health-check-fails-in-jira-server-738722400.html), troubleshooting steps will differ.

**Comment by abhattarai-athene** [comment]
Hello @bianchi2 , 
Looking at clustering section from admin, I cannot get the details about jira-1. I cannot see much from jira logs about replications. Also running telnet command from inside pods jira-1, it was not able to resolve name jira-0. 
![image](https://user-images.githubusercontent.com/71830702/131370942-8ee8ee0a-1a5f-4d97-b6e1-892b03c57ff5.png)

Below screenshot , you can see application status as running for jira-0 but not for jira-1. It only says jira-1 and jira-0 active. 
![image](https://user-images.githubusercontent.com/71830702/131371696-85811c8b-277e-4f05-887c-e13a58e46194.png)

**Comment by errcode1202** [comment]
Hi @abhattarai-athene, Jira [suffers with issues relating to indexing](https://confluence.atlassian.com/jirakb/troubleshoot-index-problems-in-jira-server-203394752.html) and clustering regardless of K8s. A number of these issues in particular are encountered more often when running Jira in a K8s cluster. These have recently been documented [here](https://atlassian.github.io/data-center-helm-charts/troubleshooting/LIMITATIONS/#jira-and-horizontal-scaling). Can you please follow [the recommended advice on scaling jira](https://atlassian.github.io/data-center-helm-charts/userguide/resource_management/RESOURCE_SCALING/#scaling-jira-safely) to see if that improves things.

**Comment by nanux** [comment]
Hi @abhattarai-athene, can you please confirm if this issue is the same as the one listed by @errcode1202? If it is the same, can you please close this ticket as we track the issue elsewhere and provide [workaround](https://atlassian.github.io/data-center-helm-charts/userguide/resource_management/RESOURCE_SCALING/#scaling-jira-safely)?

**Comment by abhattarai-athene** [comment]
The issue is resolve.
