### ISSUE TITLE
[Suggestion] - Documentation on how to import configurations such as jira-config.properties

### ISSUE THREAD

**Issue by joshua-reddish** [atlassian/data-center-helm-charts#373]
### Suggestion

It would be helpful to have an example to reference in the values.yaml of how exactly we can import configurations such as jira-config.properties into the pod so that the we can manage all aspects of our cluster from that values.yaml

### Product

Jira

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by errcode1202** [comment]
Hi @joshua-reddish there are [a number of strategies that are documented](https://atlassian.github.io/data-center-helm-charts/examples/external_libraries/EXTERNAL_LIBS/) which can be used for sharing `jira-config.properties`  amongst your pods. The easiest option might be to add the file to the `shared-home` volume using [this approach](https://atlassian.github.io/data-center-helm-charts/examples/external_libraries/EXTERNAL_LIBS/#shared-home-volume).
