### ISSUE TITLE
[Suggestion] - Allow the ability to set more than one host on the ingress object

### ISSUE THREAD

**Issue by joshua-reddish** [atlassian/data-center-helm-charts#374]
### Suggestion

 We have mutliple URLs our users access Jira with, due to legacy setups. Currently we have to manually add another host to the ingress object, but it would be nice to include it in values.yaml so we can manage everything from there.

### Product

Jira

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bianchi2** [comment]
@joshua-reddish  that's a legitimate use case indeed. While current helm charts cannot support it, you may either create another ingress object outside Helm or use [Helm post render](https://helm.sh/docs/topics/advanced/#post-rendering) to alter an ingress object, say, with [Kustomize](https://austindewey.com/2020/07/27/patch-any-helm-chart-template-using-a-kustomize-post-renderer/). 

I also think it's a nice opportunity to contribute and add something like additionalHosts to values.yaml and an ingress template.

**Comment by errcode1202** [comment]
Hi @joshua-reddish,

We're going to close this issue. If the suggestions made by @bianchi2 with regards Kustomize are not sufficient, please by all means open a PR with your proposed changes and we'll look into getting that reviewed.
