### ISSUE TITLE
Bitbucket readiness probe does not respect context path

### ISSUE THREAD

**Issue by konrad-garus** [atlassian/data-center-helm-charts#377]
### Bug

I want to deploy Bitbucket on a context path like "/bitbucket".

I'm setting `service.contextPath=/bitbucket`. It updates `SERVER_CONTEXT_PATH` in YAML (which is great), but the readiness probe is still at "/status". As a result it's never "ready". I suspect the tests may have the same issue.

To get this to work in my setup, right now I'm using the following patch.

```
kubectl patch statefulset bitbucket --type='json' \
  -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/readinessProbe/httpGet/path", "value": "/bitbucket/status"}]'

kubectl delete pod bitbucket-0
```

It looks like it could be a bug in the chart.

### Product

Bitbucket

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yzha645** [comment]
Hi @konrad-garus , thanks for raising this bug! It's now fixed, and will be included in release 1.2.0.
