### ISSUE TITLE
Shared home emptyDir prevents k8s maintenance, autoscaling, etc.

### ISSUE THREAD

**Issue by konrad-garus** [atlassian/data-center-helm-charts#379]
### Suggestion

I want to run a single node of Bitbucket. I don't need shared home, I'm not gonna use it anyway.

The chart only seems to have 2 options for shared-home: `emptyDir` or `persistentVolumeClaim`. Even if the volume is not even going to be mounted, it will still be created.

This is causing some issues later, as k8s autoscaler won't evict a pod that has local storage.

It looks like a better solution could be:
* Support `persistentVolumeClaim` for multi-node deployments.
* Do not create the shared-home volume at all for single-node deployments. What's the point of an unused `emptyDir`?

If I'm missing something and there's still some value in that `emptyDir`, perhaps it would be possible to add a switch that lets us avoid creating this volume?

### Product

Bitbucket

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jjeongatl** [comment]
Hey @konrad-garus. Thanks for raising the issue.

For the bitbucket, mounting `persistentVolume` to shared home is mandatory (regardless of number of bitbucket nodes) as it will store key contents. 

`emptyDir` will mount VM storage to pod however this is **ephemeral** volume therefore not recommended for production clusters. 

For this case, you can use custom `persistentVolume` for shared home.

- If you are already using it for local home, you can re-use this for share home by provide it as `customVolume` to shared home in values.yaml file.
- If you are not using `persistentVolume` for local home, manually create a PVC first, and provide it as `customVolume` to both local home and shared home in values.yaml file.

**Comment by konrad-garus** [comment]
I find this a little strange.

When I just generate the template with no variables (`helm template atlassian-data-center/bitbucket`), I end up with `emptyDir` for `shared-home` in my StatefulSet `volumes` section, but it's not actually mounted anywhere. So it looks like this:

```
volumeMounts:
  - name: local-home
    mountPath: "/var/atlassian/application-data/bitbucket"

# ...

volumes:
  - name: local-home
    emptyDir: {}
  - name: shared-home
    emptyDir: {}
```

Looking at statefulset.yaml, it does seem to all be conditional:

```
{{- if or .Values.volumes.sharedHome.persistentVolumeClaim.create .Values.volumes.sharedHome.customVolume }}
- name: BITBUCKET_SHARED_HOME
  value: {{ .Values.volumes.sharedHome.mountPath | quote }}
{{- end }}
```

```
volumeMounts:
  - name: local-home
    mountPath: {{ .Values.volumes.localHome.mountPath | quote }}
  {{- if or .Values.volumes.sharedHome.persistentVolumeClaim.create .Values.volumes.sharedHome.customVolume }}
  - name: shared-home
    mountPath: {{ .Values.volumes.sharedHome.mountPath | quote }}
    {{- if .Values.volumes.sharedHome.subPath }}
    subPath: {{ .Values.volumes.sharedHome.subPath | quote }}
    {{- end }}
  {{- end }}
```

I went ahead and deleted `shared-home` from `volumes`. My Bitbucket seems to be perfectly happy. The "Storage" admin page is showing shared home at `/var/atlassian/application-data/bitbucket/shared` - that is a subdirectory of my local home (which is persistent). That's exactly what I wanted.

**Comment by bianchi2** [comment]
@konrad-garus right, this works for a single node deployment, but I guess  most things in Atlassian DC Helm charts assume scaling to 2+ replicas. Since shared home needs to be RWX, it needs its own dedicated PVC (or a direct NFS volume).

emptyDir is the default - a runtime volume which is gone when the pod is recreated.

**Comment by konrad-garus** [comment]
Sure, I understand what it's for in multi-node DC. No questions there. That said, there are valid use cases for running it on a single node. Maybe you just don't need more, maybe it's a staging/test environment, etc.

That `emptyDir` is the worst of both worlds. It's useless for multi-node (and it's not even mounted!), and it's kind of breaking single-node. I had to patch it so that I could do k8s cluster maintenance, otherwise it couldn't be evicted.

**Comment by bianchi2** [comment]
Thanks for detailed explanation. I guess emptyDir here is rather a placeholder. Not sure what the best default is.

**Comment by konrad-garus** [comment]
How about not generating the `shared-home` at all?

**Comment by jjeongatl** [comment]
Hey @konrad-garus thanks for your suggestion.

What @bianchi2 mentioned is correct. The helm chart sets `emptyDir` as a default volume in case the `PVC` is not provided (At least to have something to mount).

But for bitbucket, `shared home` can be located under `local home` subpath and assuming that `PVC` was provisioned for `local home`, what you suggested might be a better option.

I created the [PR](https://github.com/atlassian/data-center-helm-charts/pull/386).

**Comment by konrad-garus** [comment]
LGTM, thank you!

**Comment by bianchi2** [comment]
@jjeongatl  was faster :) I was about to issue a similar PR. @konrad-garus thanks again for detailed explanations.

**Comment by jjeongatl** [comment]
Hey @konrad-garus PR is merged! I will close the ticket
