### ISSUE TITLE
[Suggestion] -  0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.

### ISSUE THREAD

**Issue by rcabrerizo** [atlassian/data-center-helm-charts#388]
### Suggestion

0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.

### Product

Jira

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nanux** [comment]
@rcabrerizo this looks more like an issue you are experiencing rather than a suggestion for the product. Could you please elaborate with more details? Thank you
