### ISSUE TITLE
[Bug] - Readiness probe fails, database driver unknown

### ISSUE THREAD

**Issue by ondrejbilcik** [atlassian/data-center-helm-charts#404]
### Suggestion

Hi, 

I'm running into some issues deploying the chart and would appreciate some pointers for troubleshooting.
My readiness probes are failing, with logs containing the following 
```
2022-04-08 09:52:18,765+0000 JIRA-Bootstrap FATAL      [c.a.jira.startup.JiraStartupLogger] Driver for the database Unknown not found. Ensure it is installed in the 'lib' directory.
2022-04-08 09:52:18,987+0000 JIRA-Bootstrap INFO      [c.a.jira.startup.JiraStartupLogger] Running Jira startup checks.
2022-04-08 09:52:18,987+0000 JIRA-Bootstrap FATAL      [c.a.jira.startup.JiraStartupLogger] Startup check failed. Jira will be locked.
```

I haven't been able to figure out why the database registers as Unknown, the config and the resulting env vars should be correct.

```
        database:
          type: postgres72
          driver: org.postgresql.Driver
```
```
      ATL_DB_TYPE:                   postgres72
      ATL_DB_DRIVER:               org.postgresql.Driver
```

Thanks in advance

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by errcode1202** [comment]
Hi @ondrejbilcik,

From the info you have supplied I cannot see anything immediately obvious that would cause this. For some more detail, would it be possible to supply the configured `values.yaml` you are using for this deployment?

**Comment by errcode1202** [comment]
> @ondrejbilcik also a more detailed log will help, I wonder if jdbc url is picked up.

Yes this was my thought too, is it possible the url is malformed.

**Comment by ondrejbilcik** [comment]
Hi,
Sorry, somehow missed the notifications about your replies.
Attaching the values.file and a bigger log dump. Thanks
[values.txt](https://github.com/atlassian/data-center-helm-charts/files/8511741/values.txt)
[logs.txt](https://github.com/atlassian/data-center-helm-charts/files/8511753/logs.txt)

**Comment by bianchi2** [comment]
@ondrejbilcik thanks for sharing the files. What I noticed in the logs is:

```
INFO:root:/var/atlassian/application-data/jira/dbconfig.xml exists; skipping.
```
This is how Jira entrypoint works - if the dbconfig.xml exists, it's not overwritten. Perhaps, you passed some malformed value the first time you installed the Helm chart?

I'd suggest delete helm release, make sure PVCs are deleted as well.

OR you can exec into jira container and remove `/var/atlassian/application-data/jira/dbconfig.xml` file, kill jira pod and let the entrypoint re-generate the file. It'd be great if you can cat this file and share it as well (we may see what's wrong there)

@errcode1202 may have more info on whether or not overwriting dbconfig.xml is possible in the latest versions - we did have a discussion around that recently.

**Comment by ondrejbilcik** [comment]
@bianchi2 removing the file and killing the pod worked. Thanks a bunch.
[dbconfig.txt](https://github.com/atlassian/data-center-helm-charts/files/8519975/dbconfig.txt)

**Comment by bianchi2** [comment]
@ondrejbilcik awesome! Yes, currently, if you install the chart and pass malformed db related values, dbconfig.xml is messed and **not** overwritten when you run helm upgrade. This will be fixed as far as I know.
