### ISSUE TITLE
Documentation consistency improvements

### ISSUE THREAD

**Issue by errcode1202** [atlassian/data-center-helm-charts#405]
### Suggestion

There are a few inconsistencies in the [official documentation](https://atlassian.github.io/data-center-helm-charts/) which can be improved. See https://bulldog.internal.atlassian.com/browse/DCD-1518 for details.

![image](https://user-images.githubusercontent.com/19516621/168726253-c89e0a39-dd36-435d-afd5-c9d7123eb2c1.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MrRedHead** [comment]
URL https://bulldog.internal.atlassian.com/browse/DCD-1518 is not public available?

**Comment by yzha645** [comment]
Hi @MrRedHead , DCD-1518 is an internal ticket to track this suggestion. I've updated the description to reflect the details.

**Comment by bianchi2** [comment]
Closed by https://github.com/atlassian/data-center-helm-charts/pull/463
