### ISSUE TITLE
"Base URL mismatch" on redirect

### ISSUE THREAD

**Issue by a880c05562b4f31a55f2975840ffb789** [atlassian/data-center-helm-charts#435]
### Suggestion

Hello,

I deployed Atlassian Data Center Bitbucket into a Kubernetes cluster.  All Helm tests passed.  The application is running, and with one exception ("Base URL mismatch", see below) reports no issues.  Pre-deployment I changed the service "bitbucket" type to "NodePort".  The application is behind a load balancer, which forwards traffic from port 7990 to the service NodePort.  The behavior we are observing is that the redirect eventually drops the port we have configured the load balancer to use (7990), after which we receive a HTTP status code 404 (if we also have a listener on port 80):

```
$ curl -Lv <URL>:7990/dashboard
* About to connect() to <URL> port 7990 (#0)
* Trying <IP>...
* Connected to <URL> (<IP>) port 7990 (#0)
> GET /dashboard HTTP/1.1
> User-Agent: curl/7.29.0
> Host: <URL>:7990
> Accept: */*
>
< HTTP/1.1 302
< X-AREQUESTID: @55C3QLx1044x132x0
< x-xss-protection: 1; mode=block
< x-frame-options: SAMEORIGIN
< x-content-type-options: nosniff
< Pragma: no-cache
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Cache-Control: no-cache
< Cache-Control: no-store
< Location: <URL>/login?nextUrl=%2Fdashboard
< Content-Language: en-US
< Content-Length: 0
< Date: Tue, 19 Jul 2022 17:24:50 GMT
<
* Connection #0 to host <URL> left intact
* Issue another request to this URL: '<URL>/login?nextUrl=%2Fdashboard'
* Found bundle for host <URL>: 0x1f67ff0
* About to connect() to <URL> port 80 (#1)
* Trying <IP>...
* Connected to <URL> (<IP>) port 80 (#1)
> GET /login?nextUrl=%2Fdashboard HTTP/1.1
> User-Agent: curl/7.29.0
> Host: <URL>
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Date: Tue, 19 Jul 2022 17:24:50 GMT
< Content-Type: text/html
< Content-Length: 146
< Connection: keep-alive
<
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
* Connection #1 to host <URL> left intact
```
 
or the connection times out (if we don't also have a listener on port 80).  This happens even if I exec into the pod and attempt to 'curl -Lv http://localhost:7990'.

There doesn't appear to be a way to set the application service port in the UI, but we configured Bitbucket to serve on port 7990 on deployment.

Attempts to reach "/", "/login", or "/dashboard" (for example) on deployment drop the port on redirect, but I can copy-and-paste the URL into a web browser, then add the port number and log in.  Once I get past the initial login, the port number is retained when clicking on items on the dashboard (for example).  Attempts to change the "Base URL" to include the port number in the "Administration" > "Server settings" dialogue result in the application informing me that there's a "Base URL mismatch".

In addition, the URL behind the "Bitbucket" logo in the upper left does not include the port, even if the base URL has been updated to include it.  And after updating the base URL and saving the change the link in the upper left still refers to the base URL before the update, even if the page is refreshed.

I would like to know if these URLs are hard-coded where they shouldn't be.

### Product

Bitbucket

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bianchi2** [comment]
@a880c05562b4f31a55f2975840ffb789  can you please share your values.yaml as well as svc, ingress and sts yamls from runtime? It does look like misconfiguration issue on your side. You mentioned NodePort but you don't seem to be using it anywhere in your curl commands (it should be from an ephemeral range).

Getting connection refused in a container on localhost definitely rings a bell.

**Comment by a880c05562b4f31a55f2975840ffb789** [comment]
Hello @bianchi2,

That would not be my first choice, no, but I was preparing to send you a diff of our file "values.yaml" (with URLs and IP addresses redacted) with the default product values.yaml and other artifacts when I decided to switch from a NLB to ALB with explicit forward in AWS.  I'm not sure this change resolved the problem (I can't explain it), but there was a change in behavior: the base URL now includes the port number, the URL behind the Bitbucket logo in the upper left now includes the port number, and all redirects are now to port 7990 as expected:

```
$ curl -Lv <URL>:7990/
* About to connect() to <URL> port 7990 (#0)
*   Trying <IP>...
* Connected to <URL> (<IP>) port 7990 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: <URL>:7990
> Accept: */*
>
< HTTP/1.1 302
< Date: Thu, 21 Jul 2022 14:05:23 GMT
< Content-Length: 0
< Connection: keep-alive
< X-AREQUESTID: @1W7AZ8Cx845x314x0
< x-xss-protection: 1; mode=block
< x-frame-options: SAMEORIGIN
< x-content-type-options: nosniff
< Pragma: no-cache
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Cache-Control: no-cache
< Cache-Control: no-store
< Location: <URL>:7990/dashboard
< Content-Language: en-US
<
* Connection #0 to host <URL> left intact
* Issue another request to this URL: '<URL>:7990/dashboard'
* Found bundle for host <URL>: 0x249bff0
* Re-using existing connection! (#0) with host <URL>
* Connected to <URL> (<IP>) port 7990 (#0)
> GET /dashboard HTTP/1.1
> User-Agent: curl/7.29.0
> Host: <URL>:7990
> Accept: */*
>
< HTTP/1.1 302
< Date: Thu, 21 Jul 2022 14:05:23 GMT
< Content-Length: 0
< Connection: keep-alive
< X-AREQUESTID: @1W7AZ8Cx845x315x0
< x-xss-protection: 1; mode=block
< x-frame-options: SAMEORIGIN
< x-content-type-options: nosniff
< Pragma: no-cache
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Cache-Control: no-cache
< Cache-Control: no-store
< Location: <URL>:7990/login?nextUrl=%2Fdashboard
< Content-Language: en-US
<
* Connection #0 to host <URL> left intact
* Issue another request to this URL: '<URL>:7990/login?nextUrl=%2Fdashboard'
* Found bundle for host <URL>: 0x249bff0
* Re-using existing connection! (#0) with host <URL>
* Connected to <URL> (<IP>) port 7990 (#0)
> GET /login?nextUrl=%2Fdashboard HTTP/1.1
> User-Agent: curl/7.29.0
> Host: <URL>:7990
> Accept: */*
>
< HTTP/1.1 200
< Date: Thu, 21 Jul 2022 14:05:23 GMT
< Content-Type: text/html;charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-AREQUESTID: @1W7AZ8Cx845x316x0
< x-xss-protection: 1; mode=block
< x-frame-options: SAMEORIGIN
< x-content-type-options: nosniff
< Pragma: no-cache
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Cache-Control: no-cache
< Cache-Control: no-store
< vary: accept-encoding
< Content-Language: en-US
<
<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><title>Log in - Bitbucket</title><script>
...
```

Accompanying this change, I note that the UI no longer reports a base URL mismatch, and that the "Server settings" > "Base URL" text box now reports the base URL is "http://<URL>:7990", probably retained from a previous deployment so coincidentally correct because I was unable to reliably update this value previously.  I would click "Save", then be redirected to port 80 and a "404 Not found".  I would click the back button and the value was retained, but the change had no effect.

I will try again with a NLB to determine if the behavior I was observing is reproducible, but it is clear that this problem has a solution and we are able to successfully deploy Atlassian Data Center Bitbucket.  Thanks for your time.
