### ISSUE TITLE
[Suggestion] - Ability to provide license via secret

### ISSUE THREAD

**Issue by NandoTheessen** [atlassian/data-center-helm-charts#436]
### Suggestion

Currently, it isn't possible to provide the license in a secret or in a programmatical way.

This means that for every fresh installation, manual intervention is necessary and that an engineer will need access to the license key.

I'm not familiar enough with Jira to provide a pull request that makes this a reality, but would be happy to do so if you could give me a pointer on how the license would need to be provided (env, file).

### Product

Jira

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NandoTheessen** [comment]
I chose "Jira" as a product, but I'm sure this might also apply to other products.

**Comment by bianchi2** [comment]
hi @NandoTheessen Jira [does not support unattended installation](https://github.com/atlassian/data-center-helm-charts/pull/394) but other DC products do - you can provide license secret and key in your values.yaml

**Comment by nanux** [comment]
@NandoTheessen I will close the ticket as this is dependent on support in the Jira product. When the fully automated setup is added to Jira, we will add it also to the Docker/Helm Charts.
