### ISSUE TITLE
[Suggestion] - Set Validationquery for Oracle

### ISSUE THREAD

**Issue by Zarrewitch** [atlassian/data-center-helm-charts#447]
### Suggestion

Currently the validationQuery for database connections is set to _select 1_ by default. But when configuring Oracle this leads to database Log-Errors because Oracle needs _select 1 from dual_ as validation Query. https://confluence.atlassian.com/conf76/surviving-database-connection-closures-1018769693.html

By extending the helm Charts e.g. _helpers.tpl this could be avoided/auto-detected.
`{{ if eq .Values.database.type "oracle" }}
- name: ATL_DB_VALIDATIONQUERY
  value: select 1 from dual
{{ end }}`

### Product

Confluence

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bianchi2** [comment]
hi @AlexanderOeser it's a [known issue](https://jira.atlassian.com/browse/SCALE-72) and currently the workaround is to set additional env var in value.yaml (which you know already). I think it'll be addressed soon, or else you're welcome to contribute as well.

**Comment by jjeongatl** [comment]
@AlexanderOeser We created an internal ticket to handle this suggestion
