### ISSUE TITLE
[Suggestion] - Support single-node Jira deployments

### ISSUE THREAD

**Issue by konrad-garus** [atlassian/data-center-helm-charts#458]
### Suggestion

It would be nice if the Jira chart supported single-node deployments. You don't always need the hassle and additional costs of additional volumes etc.

1. Make "shared home" optional. When it's disabled, don't create the `shared-home` volume, its corresponding volume mount, and the `JIRA_SHARED_HOME` env var.
2. Enable separation of liveness and readiness probes. Let us configure the readiness probe so that it only checks the `tcpSocket`. Jira has a nice loading splash screen, let us see that. Move the /status health check to liveness probe.

### Product

Jira

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bianchi2** [comment]
Closing in favor of https://github.com/atlassian/data-center-helm-charts/issues/459
