### ISSUE TITLE
[Suggestion] - Please check/add support of Jira 9.4.X 

### ISSUE THREAD

**Issue by SehiiRohoza** [atlassian/data-center-helm-charts#492]
### Suggestion

New LTS Jira 9.4.X was released recently. Please check if it could be used with a chart and add changes if any required.

I've tested and it works fine, but some official statement would be appreciated.

### Product

Jira

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bianchi2** [comment]
hi @SehiiRohoza It's in [maser already](https://github.com/atlassian/data-center-helm-charts/blob/main/src/main/charts/jira/Chart.yaml#L6) and will be released in 1.8.0
