### ISSUE TITLE
[Suggestion] - Bamboo Agent Volumes

### ISSUE THREAD

**Issue by timmy59100** [atlassian/data-center-helm-charts#530]
### Suggestion

For the bamboo agent helm charts we need to be able to add volumes. We need this for caches like m2 or docker images. 
Should be easy to implement like the additional volumes in Bamboo helm chart.

### Product

Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bianchi2** [comment]
@timmy59100 it's a reasonable suggestion - being able to define additional volumes and volume mounts will definitely be helpful when it comes to persisting dependencies

**Comment by bianchi2** [comment]
Fixed by https://github.com/atlassian/data-center-helm-charts/pull/619
