### ISSUE TITLE
[Suggestion] - Jira Chart - Support for priorityClassName in Statefulset

### ISSUE THREAD

**Issue by jmueller42** [atlassian/data-center-helm-charts#542]
### Suggestion

Hi,

it would be great if the priorityClassName could be set for the jira pod. Currently this is not possible, which makes it impossible to define a priority of production pods over non production pods.

Example config inside a values.yaml file: 
```yaml
jira:
  priorityClassName: "high"
```

### Product

Jira

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bianchi2** [comment]
@jmueller42 indeed, it'd be great to support that in sts template. Would you be willing to raise a PR for this feature?

**Comment by jmueller42** [comment]
@bianchi2 i will give it a try.

**Comment by jmueller42** [comment]
@bianchi2 i have created a pull request. Maybe you can review: https://github.com/atlassian/data-center-helm-charts/pull/543
