### ISSUE TITLE
[Suggestion] - Using cluster mode in kubernetes, how do nodes communicate with each other?

### ISSUE THREAD

**Issue by airsmon** [atlassian/data-center-helm-charts#555]
### Suggestion

```yaml
  clustering:
    enabled: true
```
1. There is a field clustering in helm charts value.yaml, if it is set to true, does it mean that the cluster mode is enabled?
2. In a bare-metal environment, multicast (automatic discovery) and TCP/IP (manual configuration of IP: Port) can be used. In Kubernetes, pods may not be able to automatically discover other nodes through multicast! And the Pod IP will automatically change with deletion!

May I ask you to deploy Cluster mode in Kubernetes? How to solve the problem of port 5701 communication between nodes?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bianchi2** [comment]
@airsmon yes, if clustering is enabled then you can scale statefulset to more than 1 replica. Confluence and Bitbucket use https://github.com/hazelcast/hazelcast-kubernetes plugin which will automatically discover members in the namespace.

**Comment by nhat-tong** [comment]
@bianchi2: we have enabled clustering mode when deploying Confluence Data Center using the official helm chart but this config is not taken into account (see the image below)

![MicrosoftTeams-image](https://github.com/atlassian/data-center-helm-charts/assets/7894184/8df7db30-105f-4b8e-a705-d7ffb933540f)

Either, the "join configuration" has no option is shown for "kubernetes". Is it normal ?

Thanks

**Comment by bianchi2** [comment]
@nhat-tong you need to enable clustering in values.yaml. When `confluence.clustering.enabled` is set to true, Helm chart will add Hazelcast env vars that will enable K8s Hazelcast discovery method. You won't even see this page in this case, and node discovery will be handled by a Hazelcast K8s plugin.

**Comment by nhat-tong** [comment]
@bianchi2: thanks for your answer. The config confluence.clustering.enabled is already set to true but I still see this page.
For now, it can detect my clustering but I need to choose one of discover cluster nodes: multicast, TCP/IP or AWS.

![image](https://github.com/atlassian/data-center-helm-charts/assets/7894184/98439178-7315-40fe-aaba-dd043036d33f)

How can I bypass this configuration ?

**Comment by bianchi2** [comment]
Please make sure your PVCs are empty. If confluence.cfg.xml exists, then new configuration is ignored. You may also exec into the pod and delete confluence.cfg.xml, and then restart it

**Comment by rhaskins** [comment]
What does "Please make sure your PVCs are empty." mean?

**Comment by Calikidd86** [comment]
Hey Rhaskin, the [PVC is the persistent volume claim](https://kubernetes.io/docs/concepts/storage/persistent-volumes/) for the local/shared-home directories. My understanding of the suggestion is that we'd want to make sure that there are no items located in that volume before proceeding. I hope that this helps a little.

**Comment by rhaskins** [comment]
Hi @AyoHandGod I learned from you :-) that the statement really means "kubectl delete pvc <ebs-volume-pvc>" (and also "kubectl delete pv <ebs-volume-pv>" I think, btw).
