### ISSUE TITLE
[Suggestion] - Add additionalFiles to the Bamboo-Agent Helm Chart to mount configMaps for config files like settings.xml etc.

### ISSUE THREAD

**Issue by steeu** [atlassian/data-center-helm-charts#579]
### Suggestion

Please add the additionalFiles property to the values.yaml as it ist implemented in the Bamboo chart for the Bamboo-Agent chart as well. This way, config files can be mounted and edited easily with configMaps.

### Example from the Bamboo chart:
https://github.com/atlassian/data-center-helm-charts/blob/main/src/main/charts/bamboo/values.yaml
```
# -- Additional existing ConfigMaps and Secrets not managed by Helm that should be
# mounted into service container. Configuration details below (camelCase is important!):
  # 'name'      - References existing ConfigMap or secret name.
  # 'type'      - 'configMap' or 'secret'
  # 'key'       - The file name.
  # 'mountPath' - The destination directory in a container.
# VolumeMount and Volumes are added with this name and index position, for example;
# custom-config-0, keystore-2
#
additionalFiles: []
#  - name: custom-config
#    type: configMap
#    key: log4j.properties
#    mountPath:  /var/atlassian
```

### Product

Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bianchi2** [comment]
@steeu better late than never 😃 I have raised a PR to add additionalFiles to bamboo-agent, and it'll be in the next release that will see the world pretty soon.
