### ISSUE TITLE
[Suggestion] - Provide support for compass deployments

### ISSUE THREAD

**Issue by marcellodesales** [atlassian/data-center-helm-charts#613]
### Suggestion

# Missing Product

* Will the product https://www.atlassian.com/software/compass/features be deployed by this Kubernetes effort as well?
* If so, is there a timeframe when the product is available?
* The company I work for already has Jira and Confluence and we'd love to have Compass... Is there a way to get into the program as a collaborator, since the product is still in BETA?

> **NOTE**: This is to follow the direction Atlassian is taking to get everything in Kubernetes https://community.atlassian.com/t5/Data-Center-articles/Investing-in-Kubernetes-helm-charts-and-the-end-of-support-for/ba-p/2277819

thank you
Marcello

### Product

Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bianchi2** [comment]
hi @marcellodesales I think https://jira.atlassian.com/browse/SCALE is a better place to raise such a feature request. So, far K8s compass deployment isn't on the roadmap (which can change of course).

As to collaboration, we'd definitely be excited to review a PR :)

**Comment by marcellodesales** [comment]
@bianchi2 Sounds good... Just created the ticket at https://jira.atlassian.com/browse/SCALE-102 and added notes to the ticket in regards to justification: https://community.atlassian.com/t5/Data-Center-articles/Investing-in-Kubernetes-helm-charts-and-the-end-of-support-for/ba-p/2277819

# ❓ Extra Question

* Do you happen to know if there are the Atlassian Compass docker images are available anywhere for current Atlassian customers?

**Comment by bianchi2** [comment]
Closing in favor of https://jira.atlassian.com/browse/SCALE-102. Sadly, Compass is a cloud only offering for now.
