### ISSUE TITLE
[Suggestion] - Add support for PodDisruptionBudget

### ISSUE THREAD

**Issue by Roia5** [atlassian/data-center-helm-charts#634]
### Suggestion

Support for [PodDisruptionBudget](https://kubernetes.io/docs/tasks/run-application/configure-pdb/) for the application pods.
(relevant for the Data Center version)

The use case I have:
When I am upgrading the Kubernetes version, every worker gets upgraded in a rolling upgrade yet the application pods (for example bitbucket) take a few minutes to become ready.
This means that once all workers have been upgraded (which includes node drain and cordon), there are a few minutes of downtime until the first pod becomes ready.

If needed I can work on a PR myself :)

### Product

Jira, Confluence, Bitbucket

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bianchi2** [comment]
@Roia5 https://github.com/atlassian/data-center-helm-charts/pull/636 it'll make it to the next release
