### ISSUE TITLE
[Suggestion] - Allow internal application links

### ISSUE THREAD

**Issue by reschandreas** [atlassian/data-center-helm-charts#639]
### Suggestion

Hi!

Currently the default configuration of the helm chart deployment does not add an internal service that allows the usage of internal fqdns in k8s such as `jira.atlassian.svc.cluster.local`. It would be aweomse to be able to use that feature and thus  configure the application links using those internal links without the need to use an external dependency such as loadbalancer, ingress, and dns entries.

### Product

Jira, Confluence, Bitbucket

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bianchi2** [comment]
Hi @reschandreas you can absolutely use service names in internal links. Each helm chart creates a service and you can reach this service by its name. Say, if you have deployed helm release `jira` to namespace 'jira' and `confluence` to `confluence` you can access them at `http://jira.jira.svc.cluster.local` and `http://confluence.confluence.svc.cluster.local` respectively. If helm releases are in the same namespace, it's ok to drop the namespace name from the url.

**Comment by reschandreas** [comment]
Hi @bianchi2 thanks for the response. I tried that already, but it does not work in our deployment (jira and confluence in the namespace atlassian), I get this error dialog: 
![image](https://github.com/atlassian/data-center-helm-charts/assets/16179620/fa187992-d3fc-4ebf-9491-d02fcb5313d3)

**Comment by bianchi2** [comment]
@reschandreas you may want to check if jira service exists in atlassian namespace. Can you share output from `kubectl get svc -n atlassian`? Also, you can exec into confluence pod and curl this url to see what response you get. This isn't the problem with helm charts.

**Comment by reschandreas** [comment]
From `kubectl get svc -n atlassian` I get three services, jira, confluence, and confluence-synchrony of type cluster-ip. And If use the prefix /jira (which I forgot to mention earlier, sorry) I am able to create the links but there are some other issues
![image](https://github.com/atlassian/data-center-helm-charts/assets/16179620/1d723f47-ae15-45c5-bf0b-98b214c82ba0)
![image](https://github.com/atlassian/data-center-helm-charts/assets/16179620/b578c39a-74e4-4ca9-8965-87fe6882737f)

I don't know if we did something wrong in the helm chart, or if some setting in our cluster is interfering with this. A curl in one jira pod to  http://confluence.atlassian.svc.cluster.local/confluence gives me the confluence html page

**Comment by bianchi2** [comment]
Most likely it is caused my mismatch between application link url and Jira base URL. Nothing we can do in Helm charts for that. App links should be identical to base URLs for app links to work correctly.

**Comment by reschandreas** [comment]
Oh ok, then I'll keep it as-is. Thank you so much for your support.
