### ISSUE TITLE
[Suggestion] - Allow Confluence Synchrony small CPU requests

### ISSUE THREAD

**Issue by Roia5** [atlassian/data-center-helm-charts#644]
### Suggestion

My synchrony instances (3 pods) in my test environment are hardly working yet they still had a request of 1 cpu core.

When I try to set the cpu request to less than 1 core (for example 500m), The pods will not start since the container crashes immediately.
It seems like the 'entrypoint' configmap uses 'ActiveProcessorCount' with a floored value of my cpu request, and the default is 1 core.
I am unsure if this more of a Java issue with ActiveProcessorCount so please let me know if that is the case.
Thank you!

### Product

Confluence

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bianchi2** [comment]
hi @Roia5 it does look like a Java issue. Do you have logs from the failed synchrony pod? In the meantime I'll experiment with cpu requests in my lab.

**Comment by bianchi2** [comment]
Released in 1.15.2
