### ISSUE TITLE
[Suggestion] - Create an option to Disable the Startup probe during Helm chart deployment.

### ISSUE THREAD

**Issue by hfernandes-atlassian** [atlassian/data-center-helm-charts#645]
### Suggestion

[Suggestion] - Create an option to Disable the Startup probe during Helm chart deployment.
The readiness probe and liveness probe have this option, but the startup doesn't have.

### Product

Jira

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bianchi2** [comment]
hi @hfernandes-atlassian while the suggestion makes sense, if startup probe messes up with app start somehow, you can indefinitely increase failureTreashold.

**Comment by bianchi2** [comment]
Available in 1.15.1
