### ISSUE TITLE
[Suggestion] - Upgrade to Fluentbit

### ISSUE THREAD

**Issue by rhaskins** [atlassian/data-center-helm-charts#714]
### Suggestion

Fluentd is end of life and AWS is no longer supporting/updating it (see: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-setup-logs.html). According to AWS documentation, they recommend implementing FluentBit. Are there any plans to upgrade the helm chart to FluentBit?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mattj-relativity** [comment]
This would make sending logging to loki a lot easier.  So I am a plus one.
